return {
    settings = {
        visible = true,
        locked = false,

        show_self = true,
        show_target = true,
        show_battle_targets = true,
        show_party = true,
        show_pet = true,
        show_alliance = false,
        show_empty_target = true,

        same_zone_dim = true,
        show_jobs = true,
        show_percent = true,
        show_mp = true,
        show_tp = true,
        show_cast = true,
        show_buffs = true,
        show_buff_reminders = true,
        show_target_debuffs = true,
        show_target_debuff_reminders = true,
        show_target_mobdb = true,
        show_battle_target_debuffs = true,
        hide_buff_reminders_in_towns = true,
        buff_reminder_suppressed_zone_ids = { },
        signet_reminder_enabled = true,
        signet_warning_minutes = 30,
        max_buffs = 8,
        buff_icon_size = 22,
        debuff_icon_size = 22,
        party_preview_size = 6,
        battle_target_max_entries = 8,
        mp_text_threshold = 1,
        tp_text_threshold = 1000,
        cast_text_threshold = 1,

        self_window_x = 36,
        self_window_y = 164,
        party_window_x = 36,
        party_window_y = 362,
        pet_window_x = 36,
        pet_window_y = 230,
        target_window_x = 36,
        target_window_y = 296,
        battle_window_x = 285,
        battle_window_y = 296,

        frame_width = 232,
        height = 56,
        row_height = 56,
        row_gap = 5,
        opacity = 88,
        hp_bar_height = 38,
        mp_bar_height = 18,
        tp_bar_height = 18,
        cast_bar_height = 18,
        self_frame_width = 232,
        self_height = 56,
        self_row_height = 56,
        self_row_gap = 5,
        self_opacity = 88,
        self_hp_bar_height = 38,
        self_mp_bar_height = 18,
        self_tp_bar_height = 18,
        self_cast_bar_height = 18,
        self_show_mp = true,
        self_show_tp = true,
        self_show_cast = true,
        self_mp_text_threshold = 1,
        self_tp_text_threshold = 1000,
        self_cast_text_threshold = 1,
        party_frame_width = 232,
        party_height = 56,
        party_row_height = 56,
        party_row_gap = 5,
        party_opacity = 88,
        party_hp_bar_height = 38,
        party_mp_bar_height = 18,
        party_tp_bar_height = 18,
        party_cast_bar_height = 18,
        party_show_mp = true,
        party_show_tp = true,
        party_show_cast = true,
        party_mp_text_threshold = 1,
        party_tp_text_threshold = 1000,
        party_cast_text_threshold = 1,
        party_size_layouts = {
            [1] = { x = 36, y = 362, frame_width = 232, row_height = 56, row_gap = 5, opacity = 88, columns = 1, rows = 1 },
            [2] = { x = 36, y = 362, frame_width = 232, row_height = 56, row_gap = 5, opacity = 88, columns = 1, rows = 1 },
            [3] = { x = 36, y = 362, frame_width = 232, row_height = 56, row_gap = 5, opacity = 88, columns = 1, rows = 2 },
            [4] = { x = 36, y = 362, frame_width = 232, row_height = 56, row_gap = 5, opacity = 88, columns = 1, rows = 3 },
            [5] = { x = 36, y = 362, frame_width = 232, row_height = 56, row_gap = 5, opacity = 88, columns = 1, rows = 4 },
            [6] = { x = 36, y = 362, frame_width = 232, row_height = 56, row_gap = 5, opacity = 88, columns = 1, rows = 5 },
        },
        pet_frame_width = 232,
        pet_height = 56,
        pet_row_height = 56,
        pet_row_gap = 5,
        pet_opacity = 88,
        pet_hp_bar_height = 38,
        pet_mp_bar_height = 18,
        pet_tp_bar_height = 18,
        pet_cast_bar_height = 18,
        pet_show_mp = true,
        pet_show_tp = true,
        pet_show_cast = true,
        pet_mp_text_threshold = 1,
        pet_tp_text_threshold = 1000,
        pet_cast_text_threshold = 1,
        target_frame_width = 232,
        target_height = 56,
        target_row_height = 56,
        target_row_gap = 5,
        target_opacity = 88,
        target_hp_bar_height = 38,
        target_mp_bar_height = 18,
        target_tp_bar_height = 18,
        target_cast_bar_height = 18,
        target_show_mp = false,
        target_show_tp = false,
        target_show_cast = true,
        target_mp_text_threshold = 1,
        target_tp_text_threshold = 1000,
        target_cast_text_threshold = 1,
        battle_frame_width = 232,
        battle_height = 56,
        battle_row_height = 56,
        battle_row_gap = 5,
        battle_opacity = 88,
        battle_hp_bar_height = 38,
        battle_mp_bar_height = 18,
        battle_tp_bar_height = 18,
        battle_cast_bar_height = 18,
        battle_show_mp = false,
        battle_show_tp = false,
        battle_show_cast = true,
        battle_mp_text_threshold = 1,
        battle_tp_text_threshold = 1000,
        battle_cast_text_threshold = 1,

        buff_reminders = {
            default = {
                enabled = true,
                self = true,
                players = true,
                trusts = true,
                buffs = { 'protect', 'shell' },
            },

            BST = {
                enabled = true,
                self = true,
                players = true,
                trusts = true,
                buffs = { 'protect' },
            },
        },

        target_debuff_reminders = {
            default = {
                enabled = true,
                debuffs = { 'dia', 'paralyze', 'slow' },
            },
        },
    },
}

